// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providerSet

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializedFooBarService() *FooBarService {
	barRepository := NewBarRepository()
	fooRepository := NewFooRepository()
	fooBarService := NewFooBarService(barRepository, fooRepository)
	return fooBarService
}

// injector.go:

var BarSet = wire.NewSet(NewBarRepository, NewBarService)

var FooSet = wire.NewSet(NewFooRepository, NewFooService)
